### PR TITLE
Feature: Support npm packages

### PR DESCRIPTION
**Pull request by tatsuyafw**
Hi!

This PR enables users to check npm package statuses as well as rubygems.

(demo)
pkgstatus-supports-npm

This PR does:

- Add a form for npm to the top page, and make the project controller receive npm package data.
- Bump up Font Awesome to 5 in order to display a npm icon.
- Validate whether or not top page forms are empty using JavaScript instead of html input required attributes.
- Add validations of npm package naming.

I would appreciate receiving a feedback.

### CODE REVIEW

**Comment by meganemura** [comment]
Thanks for awesome pull request.
I'll see this patch soon.

**Comment by meganemura** [comment]
LGTM!

**Comment by meganemura** [comment]
released 😄
https://pkgstatus.org/

**Comment by tatsuyafw** [comment]
@meganemura 

Thanks for merging and the release 🎉

**Pull request merged**
